#!/usr/bin/dh-exec
# source                             # target
deploy/plugins/gmaps/config.php   => etc/kopano/webapp/config-gmaps.php

deploy/plugins/gmaps/js              usr/share/kopano-webapp/plugins/gmaps
deploy/plugins/gmaps/md5             usr/share/kopano-webapp/plugins/gmaps
deploy/plugins/gmaps/php             usr/share/kopano-webapp/plugins/gmaps
deploy/plugins/gmaps/manifest.xml    usr/share/kopano-webapp/plugins/gmaps
