#!/bin/sh
# prerm script for kopano-webapp

set -e
#set -x # uncomment for verbose output

PACKAGE_NAME="kopano-webapp"

case "$1" in
    purge|remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
        ### Apache2 website deconfiguration is done by dh-apache2
        ### no special action needed
    ;;

    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
