#!/usr/bin/dh-exec
# source                     # target
deploy/config.php.dist     => etc/kopano/webapp/config.php
#deploy/kopano-webapp.conf     etc/apache2/conf-available

deploy/client                 usr/share/kopano-webapp
#deploy/plugins               usr/share/kopano-webapp
deploy/server                 usr/share/kopano-webapp

#deploy/.htaccess              etc/kopano/webapp
deploy/defaults.php           usr/share/kopano-webapp
deploy/debug.php.dist         usr/share/kopano-webapp
deploy/index.php              usr/share/kopano-webapp
deploy/init.php               usr/share/kopano-webapp
deploy/robots.txt             usr/share/kopano-webapp
deploy/kopano.php             usr/share/kopano-webapp

deploy/client/resources/fonts/KopanoWebAppDings.svg   usr/share/fonts/svg/kopanowebapp
deploy/client/resources/fonts/kopanowebappdings.eot   usr/share/fonts/eot/kopanowebapp
deploy/client/resources/fonts/kopanowebappdings.ttf   usr/share/fonts/truetype/kopanowebapp
deploy/client/resources/fonts/kopanowebappdings.woff  usr/share/fonts/woff/kopanowebapp
deploy/client/resources/fonts/kopanowebappdings.woff2 usr/share/fonts/woff/kopanowebapp
