#!/usr/bin/dh-exec
# source                                  # target
deploy/plugins/zdeveloper/config.php   => etc/kopano/webapp/config-zdeveloper.php

deploy/plugins/zdeveloper/js              usr/share/kopano-webapp/plugins/zdeveloper
deploy/plugins/zdeveloper/php             usr/share/kopano-webapp/plugins/zdeveloper
deploy/plugins/zdeveloper/resources       usr/share/kopano-webapp/plugins/zdeveloper
deploy/plugins/zdeveloper/manifest.xml    usr/share/kopano-webapp/plugins/zdeveloper
