#!/usr/bin/dh-exec
# source                                 # target
deploy/plugins/pimfolder/config.php   => etc/kopano/webapp/config-pimfolder.php

deploy/plugins/pimfolder/js              usr/share/kopano-webapp/plugins/pimfolder
deploy/plugins/pimfolder/php             usr/share/kopano-webapp/plugins/pimfolder
deploy/plugins/pimfolder/resources       usr/share/kopano-webapp/plugins/pimfolder
deploy/plugins/pimfolder/manifest.xml    usr/share/kopano-webapp/plugins/pimfolder
